name: Push Docker images to GHCR

on:
  push:
    tags:
      - '**'
    branches:
      - '**'

jobs:
  build-base-image:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/mapserver-base
      - uses: docker/build-push-action@v2
        with:
          file: base.Dockerfile
          tags: ${{ steps.docker_meta.outputs.tags }}
          push: true

  build-example-image:
    runs-on: ubuntu-latest
    needs: build-base-image
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/mapserver-example
      - uses: docker/build-push-action@v2
        with:
          file: example.Dockerfile
          tags: ${{ steps.docker_meta.outputs.tags }}
          push: true
