name: Push Docker images to GHCR

on:
  push:
    tags:
      - '**'
    branches:
      - '**'

jobs:
  build-base-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build base Docker image
        run: |
          DOCKER_TAG=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker buildx build -f base.Dockerfile -t ghcr.io/${OWNER}/mapserver-base:${DOCKER_TAG} \
                                                 -t ghcr.io/${OWNER}/mapserver-base:latest .
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push base Docker image to GHCR
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/${OWNER}/mapserver-base --all-tags
  build-example-image:
    runs-on: ubuntu-latest
    needs: build-base-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build example Docker image
        run: |
          DOCKER_TAG=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker buildx build -f example.Dockerfile -t ghcr.io/${OWNER}/mapserver-example:${DOCKER_TAG} \
                                                    -t ghcr.io/${OWNER}/mapserver-example:latest .

      - name: Push example Docker image to GHCR
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/${OWNER}/mapserver-example --all-tags
